frontend/models/Author.php
<?php

namespace frontend\models;

/**
 * This is the model class for table "author".
 *
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $birthdate
 * @property integer $rating
 */
class Author extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{author}}';
    }
    
    public function rules()
    {
        return [
            [['first_name', 'last_name'], 'required'],
            [['first_name', 'last_name'], 'string', 'max' => 25],
            [['birthdate'], 'date', 'format' => 'php:Y-m-d'],
            [['rating'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'birthdate' => 'Birthdate',
            'rating' => 'Rating',
        ];
    }

}

frontend/controllers/AuthorController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Author;

class AuthorController extends \yii\web\Controller
{
    public function actionCreate()
    {
        $model = new Author();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Author added');
            return $this->redirect(['author/index']);
        }
        
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $model = Author::findOne($id);
        $model->delete();
        Yii::$app->session->setFlash('success', 'Author has been deleted');
        return $this->redirect(['author/index']);
    }

    public function actionIndex()
    {
        $authorsList = Author::find()->all();
        
        return $this->render('index', [
            'authorsList' => $authorsList,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = Author::findOne($id);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Author has been updated');
            return $this->redirect(['author/index']);
        }
        
        return $this->render('update', [
            'model' => $model,
        ]);
    }

}

frontend/views/author/create.php
<?php
/* @var $this yii\web\View */
/* $var $model frontend\models\Author */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<h1>Create new author</h1>

<?php $form = ActiveForm::begin(); ?>

    <?php echo $form->field($model, 'first_name'); ?>

    <?php echo $form->field($model, 'last_name'); ?>

    <?php echo $form->field($model, 'birthdate'); ?>

    <?php echo $form->field($model, 'rating'); ?>


    <?php echo Html::submitButton('Save', [
        'class' => 'btn btn-primary'
    ]); ?>

<?php ActiveForm::end();

frontend/views/author/delete.php
<?php
/* @var $this yii\web\View */
?>
<h1>author/delete</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

frontend/views/author/index.php
<?php
/* @var $this yii\web\View */
/* @var $authorsList[] frontend\models\Author */
use yii\helpers\Url;
?>
<h1>Authors</h1>

<br>

<a href="<?php echo Url::to(['author/create']); ?>" class="btn btn-primary">Create new author</a>

<br><br>

<table class="table table-condensed">
    <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <?php foreach ($authorsList as $author): ?>
        <tr>
            <td><?php echo $author->id; ?></td>
            <td><?php echo $author->first_name; ?></td>
            <td><?php echo $author->last_name; ?></td>
            <td><a href="<?php echo Url::to(['author/update', 'id' => $author->id]); ?>">Edit</a></td>
            <td><a href="<?php echo Url::to(['author/delete', 'id' => $author->id]); ?>">Delete</a></td>
            <td></td>
        </tr>
    <?php endforeach; ?>
</table>

frontend/views/author/update.php
<?php
/* @var $this yii\web\View */
/* $var $model frontend\models\Author */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<h1>Update author #ID: <?php echo $model->id; ?></h1>

<?php $form = ActiveForm::begin(); ?>

    <?php echo $form->field($model, 'first_name'); ?>

    <?php echo $form->field($model, 'last_name'); ?>

    <?php echo $form->field($model, 'birthdate'); ?>

    <?php echo $form->field($model, 'rating'); ?>


    <?php echo Html::submitButton('Save', [
        'class' => 'btn btn-primary'
    ]); ?>

<?php ActiveForm::end();